# Generated by Django 4.1.1 on 2022-10-13 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SCPEuclid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_object', models.CharField(max_length=255, verbose_name='Название объекта фонда')),
                ('description', models.CharField(max_length=6000, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='scp_euclid/', verbose_name='Изображение')),
                ('content', models.CharField(max_length=5000, verbose_name='Условия содержания')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='SCPKeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_object', models.CharField(max_length=255, verbose_name='Название объекта фонда')),
                ('description', models.CharField(max_length=6000, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='scp_keter', verbose_name='Изображение')),
                ('content', models.CharField(max_length=5000, verbose_name='Условия содержания')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='SCPSafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_object', models.CharField(max_length=100, verbose_name='Название объекта')),
                ('description', models.CharField(max_length=6000, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='scp_safe/', verbose_name='Изображение')),
                ('content', models.CharField(max_length=5000, verbose_name='Условия содержания')),
            ],
        ),
        migrations.CreateModel(
            name='SCPThaumiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_object', models.CharField(max_length=255, verbose_name='Название объекта фонда')),
                ('description', models.CharField(max_length=6000, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='scp_thaumiel/', verbose_name='Изображение')),
                ('content', models.CharField(max_length=5000, verbose_name='Условия содержания')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='SCPAllClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scp_euclid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scp_base.scpeuclid', verbose_name='Объект класса Евклид')),
                ('scp_keter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scp_base.scpketer', verbose_name='Объект класса Кетер')),
                ('scp_safe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scp_base.scpsafe', verbose_name='Объект класса Безопасный')),
                ('scp_thaumiel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scp_base.scpthaumiel', verbose_name='Объект класса Таумиель')),
            ],
        ),
    ]
