# Generated by Django 4.0.6 on 2022-10-17 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scp_base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scpsafe',
            options={'ordering': ('title_object',), 'verbose_name': 'временная модель', 'verbose_name_plural': 'временные модели'},
        ),
    ]
