# Generated by Django 4.1.1 on 2022-10-14 11:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='expirations_date',
            field=models.DateField(default=datetime.datetime(2025, 10, 13, 17, 37, 17, 37597), verbose_name='Срок годности'),
        ),
    ]
