# Generated by Django 4.0.6 on 2022-10-17 12:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_alter_card_expirations_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='expirations_date',
            field=models.DateField(default=datetime.datetime(2025, 10, 16, 18, 46, 51, 315327), verbose_name='Срок годности'),
        ),
    ]
